version: '3.8'

services:
  neo4j:
    image: neo4j
    container_name: my_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ~/neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: always
