apm-server:
  host: "0.0.0.0:8200"
  rum:
    enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: "http"

setup.kibana:
  host: "kibana:5601"

logging.json: true
monitoring.enabled: true